services:
  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: project_digital_twin
      POSTGRES_USER: project
      POSTGRES_PASSWORD: project
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
