"""Compatibility entrypoint for the FastAPI application."""

from .main_core.app_factory import create_app
from .main_core.dependencies import (
    authorize_header as _authorize_header,
    build_store as _build_store,
    current_principal,
    get_store,
    organize_group_state as _organize_group_state,
    organize_membership_state as _organize_membership_state,
)
from .main_core.request_context import request_metrics
from .shared.schemas import (
    ApprovalRequest,
    ContractorCreate,
    DocumentImportRequest,
    FileImportRequest,
    FieldPackageCreate,
    GeometryRequest,
    ImportRequest,
    ObservationCreate,
    OrganizeGroupCreate,
    OrganizeGroupPatch,
    OrganizeLifecycleRequest,
    OrganizeMembershipRequest,
    OrganizeTagCreate,
    OrganizeWriteBackExecuteRequest,
    OrganizeWriteBackPreviewRequest,
    ProjectCreate,
    ProjectDelete,
    RestoreJobCreate,
    WorkPackageCreate,
    WriteJobComplete,
    WriteJobCreate,
    WriteJobFailureRequest,
    SyncBatchRequest,
    SyncBatchResponse,
    SyncMutationAck,
    SyncMutationItem,
)


store = get_store()
app = create_app()

__all__ = [
    "ApprovalRequest",
    "ContractorCreate",
    "DocumentImportRequest",
    "FileImportRequest",
    "FieldPackageCreate",
    "GeometryRequest",
    "ImportRequest",
    "ObservationCreate",
    "OrganizeGroupCreate",
    "OrganizeGroupPatch",
    "OrganizeLifecycleRequest",
    "OrganizeMembershipRequest",
    "OrganizeTagCreate",
    "OrganizeWriteBackExecuteRequest",
    "OrganizeWriteBackPreviewRequest",
    "ProjectCreate",
    "ProjectDelete",
    "RestoreJobCreate",
    "SyncBatchRequest",
    "SyncBatchResponse",
    "SyncMutationAck",
    "SyncMutationItem",
    "WorkPackageCreate",
    "WriteJobComplete",
    "WriteJobCreate",
    "WriteJobFailureRequest",
    "_authorize_header",
    "_build_store",
    "_organize_group_state",
    "_organize_membership_state",
    "app",
    "current_principal",
    "request_metrics",
    "store",
]
